<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="6" failures="1" name="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" time="4.215" errors="0" skipped="0">
  <properties>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="shared.loader" value=""/>
    <property name="org.eclipse.gemini.web.tomcat.config.path" value="configuration/tomcat-server.xml"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
  </properties>
  <testcase classname="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" name="testIfReturnsAllEventsExistingForUserWithOffsetAndLimit" time="0.707"/>
  <testcase classname="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" name="testIfReturnsAllExceptExcludedAndManuallyCreated" time="0.822"/>
  <testcase classname="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" name="testIfReturnsAllEventsExistingForUserByDefault" time="0.502">
    <rerunFailure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest.testIfReturnsAllEventsExistingForUserByDefault(UserEventRepositoryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.acme.junit.framework.RunAsTestCase.runMethod(RunAsTestCase.java:190)
	at com.acme.junit.framework.RunAsTestCase.access$0(RunAsTestCase.java:184)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:205)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:1)
	at com.acme.util.Executor.checkedCall(Executor.java:92)
	at com.acme.core.internal.spi.CallAs.principal(CallAs.java:76)
	at com.acme.junit.framework.RunAsTestCase.runAs(RunAsTestCase.java:134)
	at com.acme.junit.framework.RunAsTestCase.runTestAs(RunAsTestCase.java:79)
	at com.acme.junit.framework.RunAsTestCase.runBare(RunAsTestCase.java:48)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.rerunTests(JUnitRunner.java:328)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.runTests(JUnitRunner.java:287)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.access$2(JUnitRunner.java:258)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner$1.run(JUnitRunner.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</rerunFailure>
    <rerunFailure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest.testIfReturnsAllEventsExistingForUserByDefault(UserEventRepositoryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.acme.junit.framework.RunAsTestCase.runMethod(RunAsTestCase.java:190)
	at com.acme.junit.framework.RunAsTestCase.access$0(RunAsTestCase.java:184)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:205)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:1)
	at com.acme.util.Executor.checkedCall(Executor.java:92)
	at com.acme.core.internal.spi.CallAs.principal(CallAs.java:76)
	at com.acme.junit.framework.RunAsTestCase.runAs(RunAsTestCase.java:134)
	at com.acme.junit.framework.RunAsTestCase.runTestAs(RunAsTestCase.java:79)
	at com.acme.junit.framework.RunAsTestCase.runBare(RunAsTestCase.java:48)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.rerunTests(JUnitRunner.java:328)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.runTests(JUnitRunner.java:287)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.access$2(JUnitRunner.java:258)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner$1.run(JUnitRunner.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</rerunFailure>
    <rerunFailure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest.testIfReturnsAllEventsExistingForUserByDefault(UserEventRepositoryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.acme.junit.framework.RunAsTestCase.runMethod(RunAsTestCase.java:190)
	at com.acme.junit.framework.RunAsTestCase.access$0(RunAsTestCase.java:184)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:205)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:1)
	at com.acme.util.Executor.checkedCall(Executor.java:92)
	at com.acme.core.internal.spi.CallAs.principal(CallAs.java:76)
	at com.acme.junit.framework.RunAsTestCase.runAs(RunAsTestCase.java:134)
	at com.acme.junit.framework.RunAsTestCase.runTestAs(RunAsTestCase.java:79)
	at com.acme.junit.framework.RunAsTestCase.runBare(RunAsTestCase.java:48)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.rerunTests(JUnitRunner.java:328)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.runTests(JUnitRunner.java:287)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.access$2(JUnitRunner.java:258)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner$1.run(JUnitRunner.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</rerunFailure>
    <rerunFailure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest.testIfReturnsAllEventsExistingForUserByDefault(UserEventRepositoryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.acme.junit.framework.RunAsTestCase.runMethod(RunAsTestCase.java:190)
	at com.acme.junit.framework.RunAsTestCase.access$0(RunAsTestCase.java:184)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:205)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:1)
	at com.acme.util.Executor.checkedCall(Executor.java:92)
	at com.acme.core.internal.spi.CallAs.principal(CallAs.java:76)
	at com.acme.junit.framework.RunAsTestCase.runAs(RunAsTestCase.java:134)
	at com.acme.junit.framework.RunAsTestCase.runTestAs(RunAsTestCase.java:79)
	at com.acme.junit.framework.RunAsTestCase.runBare(RunAsTestCase.java:48)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.rerunTests(JUnitRunner.java:328)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.runTests(JUnitRunner.java:287)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.access$2(JUnitRunner.java:258)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner$1.run(JUnitRunner.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</rerunFailure>
    <rerunFailure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest.testIfReturnsAllEventsExistingForUserByDefault(UserEventRepositoryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.acme.junit.framework.RunAsTestCase.runMethod(RunAsTestCase.java:190)
	at com.acme.junit.framework.RunAsTestCase.access$0(RunAsTestCase.java:184)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:205)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:1)
	at com.acme.util.Executor.checkedCall(Executor.java:92)
	at com.acme.core.internal.spi.CallAs.principal(CallAs.java:76)
	at com.acme.junit.framework.RunAsTestCase.runAs(RunAsTestCase.java:134)
	at com.acme.junit.framework.RunAsTestCase.runTestAs(RunAsTestCase.java:79)
	at com.acme.junit.framework.RunAsTestCase.runBare(RunAsTestCase.java:48)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.rerunTests(JUnitRunner.java:328)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.runTests(JUnitRunner.java:287)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.access$2(JUnitRunner.java:258)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner$1.run(JUnitRunner.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</rerunFailure>
    <failure message="expected:&lt;2&gt; but was:&lt;3&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;3&gt;
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest.testIfReturnsAllEventsExistingForUserByDefault(UserEventRepositoryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.acme.junit.framework.RunAsTestCase.runMethod(RunAsTestCase.java:190)
	at com.acme.junit.framework.RunAsTestCase.access$0(RunAsTestCase.java:184)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:205)
	at com.acme.junit.framework.RunAsTestCase$CheckedRunnableAdapter.call(RunAsTestCase.java:1)
	at com.acme.util.Executor.checkedCall(Executor.java:92)
	at com.acme.core.internal.spi.CallAs.principal(CallAs.java:76)
	at com.acme.junit.framework.RunAsTestCase.runAs(RunAsTestCase.java:134)
	at com.acme.junit.framework.RunAsTestCase.runTestAs(RunAsTestCase.java:79)
	at com.acme.junit.framework.RunAsTestCase.runBare(RunAsTestCase.java:48)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.runTests(JUnitRunner.java:284)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner.access$2(JUnitRunner.java:258)
	at com.github.nfalco79.junit4osgi.runner.internal.JUnitRunner$1.run(JUnitRunner.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase classname="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" name="testIfReturnsAllEventsExistingForUserByDefaultWithOffset" time="1.028"/>
  <testcase classname="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" name="testIfSkipsManualUserActivationEvent" time="0.655"/>
  <testcase classname="com.acme.slt.user.core.test.internal.persistence.UserEventRepositoryTest" name="testIfReturnsAllEventsExistingForUserWithLimit" time="0.501"/>
</testsuite>